In [42]:
import pandas as pd
from sklearn.model_selection import train_test_split # use for splitting the dataset into training and testing sets
from sklearn.preprocessing import StandardScaler, LabelEncoder # use for scaling the features and encoding the target variable
import pickle  # use for saving the encoders and scaler

In [43]:
# Load the dataset 
data = pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [44]:
## Drop irrelevent columns
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [45]:
## Encode categorical variable 
label_encoder_gender = LabelEncoder() # use for encoding the gender column
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France       0  ...               1        101348.88       1
1          608     Spain       0  ...               1        112542.58       0
2          502    France       0  ...               0        113931.57       1
3          699    France       0  ...               0         93826.63       0
4          850     Spain       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [46]:
## Onehot encode 'Geography'
from sklearn.preprocessing import OneHotEncoder

onehot_encoder_geo = OneHotEncoder(sparse_output=False)
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [47]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [48]:
geo_encoded_df =  pd.DataFrame(geo_encoder, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [49]:
## Combine one hot encoder columns with the original data
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [50]:
## Save the encoders and scaler

with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

In [51]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [52]:
## Divide the dataset into independent and dependent features 
X = data.drop('Exited', axis=1) ## input data
y = data['Exited']           ## uutput data  

## Split the data in training and testing sets 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## scale these featurs 
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train) ## it will readed and transform as used fit 
X_test=scaler.transform(X_test)   ## it will only transform the data

In [53]:
scaler

StandardScaler()

In [54]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [55]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

## ANN Implementation

In [56]:
import tensorflow as tf
from tensorflow.keras.models import Sequential # use for creating a sequential model
from tensorflow.keras.layers import Dense  # use for creating the layers of the model
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard # needed for early stopping and tensorboard
import datetime

In [57]:
(X_train.shape[1],)

(12,)

In [58]:
# Build our ANN Model 

model = Sequential([
    Dense(64,activation='relu', input_shape=(X_train.shape[1],)),  # use for creating the layers(HL1) of the model
    Dense(32, activation='relu'), ## use for creating the layers(HL2) of the model 
    Dense(1, activation='sigmoid') ## use for creating the output layers(OL) of the model
])

In [59]:
model.summary()

Model: "sequential_4"

_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 64)                832

 dense_7 (Dense)             (None, 32)                2080

 dense_8 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [60]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy() ## use for calculating the loss of the model
loss

In [61]:
## compile the model 
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [62]:
## Setup the Tensorboard 
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [63]:
## Set up Early stopping 

early_stopping_callback = EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [64]:
## Train the model

history=model.fit(X_train, y_train, validation_data=(X_test,y_test), epochs=100, callbacks=[tensorflow_callback, early_stopping_callback])

Epoch 1/100
250/250 [==============================] - 3s 7ms/step - loss: 0.3967 - accuracy: 0.8353 - val_loss: 0.3526 - val_accuracy: 0.8595
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3549 - accuracy: 0.8561 - val_loss: 0.3478 - val_accuracy: 0.8565
Epoch 3/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3486 - accuracy: 0.8584 - val_loss: 0.3400 - val_accuracy: 0.8590
Epoch 4/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3426 - accuracy: 0.8596 - val_loss: 0.3434 - val_accuracy: 0.8640
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3402 - accuracy: 0.8602 - val_loss: 0.3379 - val_accuracy: 0.8620
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3370 - accuracy: 0.8619 - val_loss: 0.3535 - val_accuracy: 0.8465
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3389 - accuracy: 0.8604 - val_loss: 0.3351 - val_accuracy: 0.8595
Epoch 8/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3339 - accuracy: 0.8626 - val_loss: 0.3456 - val_accuracy: 0.8600
Epoch 9/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3332 - accuracy: 0.8622 - val_loss: 0.3520 - val_accuracy: 0.8495
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3298 - accuracy: 0.8651 - val_loss: 0.3504 - val_accuracy: 0.8495
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3293 - accuracy: 0.8634 - val_loss: 0.3468 - val_accuracy: 0.8590
Epoch 12/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3269 - accuracy: 0.8695 - val_loss: 0.3572 - val_accuracy: 0.8505

In [65]:
model.save('model.h5')

c:\Users\saura\OneDrive\Desktop\testing\genai\projects\ANNproject\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [66]:
## Load Tensorboard Extension

%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [68]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6007 (pid 16908), started 0:00:13 ago. (Use '!kill 16908' to kill it.)